### ISSUE TITLE
(bug) no idea what this is but i cant get past please wait again

### ISSUE THREAD

**Issue by lovebug0706** [werwolf2303/SpotifyXP#11]
heres the code
`[timeout] okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335)
okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
com.spotifyxp.deps.xyz.gianlu.librespot.core.Session.lambda$createClient$1(Session.java:174)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
com.spotifyxp.deps.xyz.gianlu.librespot.core.ApResolver.request(ApResolver.java:82)
com.spotifyxp.deps.xyz.gianlu.librespot.core.ApResolver.fillPool(ApResolver.java:53)
com.spotifyxp.deps.xyz.gianlu.librespot.core.ApResolver.<init>(ApResolver.java:49)
com.spotifyxp.deps.xyz.gianlu.librespot.core.Session.<init>(Session.java:136)
com.spotifyxp.deps.xyz.gianlu.librespot.core.Session.<init>(Session.java:78)
com.spotifyxp.deps.xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1056)
com.spotifyxp.utils.PlayerUtils.buildPlayer(PlayerUtils.java:48)
com.spotifyxp.api.SpotifyAPI$Player.<init>(SpotifyAPI.java:85)
com.spotifyxp.Initiator.main(Initiator.java:183)`

plz fix

**Comment by werwolf2303** [comment]
This looks like an Connection issue. Try turning your wifi off and on
