### ISSUE TITLE
Crash with bad creditentials & can't reopen app

### ISSUE THREAD

**Issue by Sleora** [werwolf2303/SpotifyXP#14]
Everything is in the title, when I type a bad password the whole thing crash and I'm forced to quit everything. When I try to reopen it, I'm gretted with that :

![Capture d’écran 2023-04-21 220520](https://user-images.githubusercontent.com/47717666/233725216-d0f8627f-0cb7-4eb3-ab6a-e4d50f22ea68.png)

The only solution I found to unlock everything was to delete everything in C:\Documents and Settings\[USER]\Application Data\SpotifyXP and reinstall.

![Capture d’écran 2023-04-21 221129](https://user-images.githubusercontent.com/47717666/233726171-660ef957-2ad8-47ca-bc42-caccc854d865.png)

I suggest adding a feature that, when you enter a bad loggin, instead of CRASHING THE WHOLE THING, it shows you a "try again" button.

**Comment by Sleora** [comment]
I suggest adding a feature that, when you enter a bad loggin, instead of CRASHING THE WHOLE THING, it shows you a "try again" button.

**Comment by werwolf2303** [comment]
I thought I already implemented that. I fix this as soon as I'am done with implementing svg

**Comment by werwolf2303** [comment]
Upcoming version 1.8: Bad credentials are fixed and you can now click on cancel and spotifyxp will start anyway
