### ISSUE TITLE
Theme having issue on XP

### ISSUE THREAD

**Issue by lovebug0706** [werwolf2303/SpotifyXP#2]
dont know what it is, but heres my prompt
````
C:\Documents and Settings\MacBack\My Documents\Downloads>java -jar SpotifyXP.jar

Exception in thread "main" java.lang.IllegalArgumentException: No enum constant
com.spotifyxp.designs.Theme.settings.ui.theme
        at java.lang.Enum.valueOf(Unknown Source)
        at com.spotifyxp.designs.Theme.valueOf(Theme.java:3)
        at com.spotifyxp.Initiator.main(Initiator.java:60)

C:\Documents and Settings\MacBack\My Documents\Downloads>
````

IDK if you guys can fix this, but I cant. I have no knowledge on Java.
Note that this was with Nightly Build 13.

UPDATE 1: I just tried it with Nightly Build 14 and it still doesnt work. Same error.

**Comment by werwolf2303** [comment]
Can you check if under AppData there is a folder named SpotifyXP and if so can you give me the contents of the file config.properties of course without username and password

**Comment by werwolf2303** [comment]
Should be good now with the newest nightly build
