### ISSUE TITLE
SpotifyXP hangs when clicking on the Lyric panel

### ISSUE THREAD

**Issue by lesar8** [werwolf2303/SpotifyXP#24]
Hi, SpotifyXP will hangs soon after i click on the Lyric panel (to copy song lyrics). Hopefully this issue will be fixed.

![Screenshot](https://github.com/werwolf2303/SpotifyXP/assets/133925958/05c51328-7f03-4595-8f88-aac10922453a)

**Comment by Gonimbrasia** [comment]
It seems to happen if the track is playing. If you pause playback and then bring up the lyric panel, you can then select and copy the full lyrics.

**Comment by werwolf2303** [comment]
This part of the program was also reverse engineered so it can be that something is missing
