### ISSUE TITLE
Invalid Login problem (SpotifyXP V1.9)

### ISSUE THREAD

**Issue by omerxxd** [werwolf2303/SpotifyXP#25]
I'm using Windows XP SP3 and when i'm entering Spotify credentials i get an error and it won't let me log in even though i'm entering my e-mail and password correctly. (I was having the same issue on V1.8 too.)
![spotify xp v1 9 error](https://github.com/werwolf2303/SpotifyXP/assets/125218302/90afce2b-7b88-4564-afdd-8082cff44b66)

**Comment by werwolf2303** [comment]
Do you have a premium account or a free one
