### ISSUE TITLE
SpotifyXP stuck on Please Wait...

### ISSUE THREAD

**Issue by lovebug0706** [werwolf2303/SpotifyXP#3]
Its me again, and its still not working. The theme loaded this time, but it has an error and it sits at the please wait.
Heres the code:  `SLP4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLP4J: Defaulting to no-operation (NOP) logger implementation
SLP4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: no enum constant com.spotifyxp.deps.xyz.gianlu.librespot.audio.decoders.AudioQuality.valueOf (AudioQuality.java:28)
at com.spotifyxp.utils.PlayerUtils.buildPlayer(PlayerUtils.java:38)
at com.spotifyxp.api.SpotifyAPI$Player.<init>(SpotifyAPI.java:77)
at com.spotifyxp.initiator.main(Initiator.java:121)`

IDK if its my PC or if im forgetting something or anything, but its not working.

This is with Version 1.6 Hotfix.

Edit: I tried it with Version 1.5, and also the one where you fixed issue 2, and it still doesnt work. It isnt the theme though, as the setup loaded on 1.6.

**Comment by werwolf2303** [comment]
Send me the config.properties inside appdata/SpotifyXP please

**Comment by werwolf2303** [comment]
I figured it out just delete the SpotifyXP folder in AppData and try again

**Comment by ojt1998** [comment]
I had a similar issue when I typo’d my password. Like you say, deleting the SpotifyXP folder works and then allows you to log back in.

**Comment by werwolf2303** [comment]
Fixed in upcoming version 1.7
