### ISSUE TITLE
cannot create api

### ISSUE THREAD

**Issue by SuckyBuckyYT** [werwolf2303/SpotifyXP#30]
it says created api but its stuck on it and it comes up with the login page and when i try to login it says "[java.lang.NullPointerException] com.spotifyxp.api.SpotifyAPI$Player.<init>(SpotifyAPI.java:78)
com.spotifyxp.Initiator.main(Initiator.java:182)"

**Comment by werwolf2303** [comment]
Please provide me the output of "java -jar SpotifyXP.jar --setup-complete --debug"

**Comment by KarlS0808** [comment]
> Please provide me the output of "java -jar SpotifyXP.jar --setup-complete --debug" in cmd

Mine gets this: https://imgur.com/a/jv0LSEE

**Comment by SuckyBuckyYT** [comment]
Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\Admin\SpotifyXP>java -jar SpotifyXP.jar --setup-comple
te --debug
Module [INFO ] Loaded aps into pool: {accesspoint=[ap-gae2.spotify.com:4070, ap-
gae2.spotify.com:443, ap-gae2.spotify.com:80, ap-gue1.spotify.com:4070, ap-guc3.
spotify.com:443, ap-gew1.spotify.com:80], dealer=[gae2-dealer.spotify.com:443, g
ue1-dealer.spotify.com:443, guc3-dealer.spotify.com:443, gew1-dealer.spotify.com
:443], spclient=[gae2-spclient.spotify.com:443, gue1-spclient.spotify.com:443, g
uc3-spclient.spotify.com:443, gew1-spclient.spotify.com:443]}
Module [INFO ] Created new session! {deviceId: 2ffa447bcc2532eab1496e0436fe7eb36
7015918, ap: ap-gae2.spotify.com:80, proxy: false}
Module [INFO ] Connected successfully!
SpotifyXP [THROWABLE ] com.spotifyxp.api.SpotifyAPI$Player.<init>(SpotifyAPI.jav
a:78)
SpotifyXP [THROWABLE ] com.spotifyxp.Initiator.main(Initiator.java:182)

**Comment by werwolf2303** [comment]
Download the newest nightly version and run it with "java -jar SpotifyXP.jar --setup-complete --debug"

**Comment by werwolf2303** [comment]
Ok nevermind. This problem appears also on a laptop I have. When I have time tomorrow I will look into that

**Comment by werwolf2303** [comment]
For me its working again somehow
