### ISSUE TITLE
Expand playlist/albums song limit

### ISSUE THREAD

**Issue by lesar8** [werwolf2303/SpotifyXP#31]
Hi, it seems like there is currently a limit of 100 songs in a playlist and 50 songs in album. I can't scroll beyond that. Do you think this can be improved? Thanks!

**Comment by werwolf2303** [comment]
Can you give me an example oft his

**Comment by lesar8** [comment]
> Can you give me an example oft his

Hi, just search the keyword "1000 songs"  with "Search Playlists" filter, then access any results showed. It's not possible to scroll more than 100 songs, even though the playlist has 1000 songs.
Picture: [https://imgtr.ee/images/2023/06/14/TShpn.jpg](https://imgtr.ee/images/2023/06/14/TShpn.jpg)

For album, "Chrono Cross Original Album" is a great example. This album has 67 songs, but only 50 songs showed.
Picture: [https://imgtr.ee/images/2023/06/14/TSevq.jpg](https://imgtr.ee/images/2023/06/14/TSevq.jpg)

**Comment by lesar8** [comment]
Hi, i re-opened this ticket because the commit [bc9c18a](https://github.com/werwolf2303/SpotifyXP/commit/bc9c18a1b338d8e57f425355a9bdd0771e3e63ec) that applied the fix is now causing a new issue. Trying to access any playlist/album with more than 100 songs will hang the application! Previous builds still able to access them.

**Comment by werwolf2303** [comment]
SpotifyXP loops over every title in this song that means it takes a while but what I can do is processing all that in a thread.

**Comment by lesar8** [comment]
Hi, I'm sorry I did no

> I will finish the Canvas implementation then I will fix this

Hi, I'm sorry I did not read your reply. Please check my new opened ticket.
