### ISSUE TITLE
Commit "7123f9d" issue

### ISSUE THREAD

**Issue by lesar8** [werwolf2303/SpotifyXP#33]
Hi, the commit 7123f9d introduced an issue that when trying to access any playlist with more than 150 songs, it will keeps loading songs from the playlist non-stop and seems to loop forever.

**Comment by lesar8** [comment]
Hi! Sorry for the late response, unfortunately version 2.0 has not corrected this issue. Does that happen on your side as well?

**Comment by werwolf2303** [comment]
I never tried it. It seems weird that it doesnt work because on the api site I am fetching all songs

**Comment by werwolf2303** [comment]
Can you make a video with obs and post it on youtube that I can see it. 
When yes please execute SpotifyXP with --setup-complete --debug

**Comment by lesar8** [comment]
> Can you make a video with obs and post it on youtube that I can see it. When yes please execute SpotifyXP with --setup-complete --debug

Hi! I'm using a software to record a MP4 video from my pc screen, compressed to ZIP archive and attached it here. I think the video's slow framerate is actually helpful to analyze the debug screen. Hope this helps!

[SpotifyXP Recorded.zip](https://github.com/werwolf2303/SpotifyXP/files/12552630/SpotifyXP.Recorded.zip)

**Comment by werwolf2303** [comment]
Spotify API says it has 468 songs. I can make a debug build later that has a right click option that shows how many songs are in the list

**Comment by werwolf2303** [comment]
Try this one: http://spotifyxp.werwolf2303.de/SpotifyXP-TestBuild.jar

**Comment by lesar8** [comment]
> Try this one: http://spotifyxp.werwolf2303.de/SpotifyXP-TestBuild.jar

Hi, i just tried it but the problem still remains.

**Comment by werwolf2303** [comment]
Ok thats weird I will continue investigating and hopefully fix it

**Comment by werwolf2303** [comment]
Please say its fixed

**Comment by lesar8** [comment]
> Please say its fixed

Yes yes, it is fixed. Thank you!!  Would you mind to have a look at the "Playlists" tab? There is a restriction that only about 100 songs appears, even though my playlist has more than thousand songs.. I can bypass this problem by searching my playlist through the "Search" tab, but it's a bit time consuming you know :-)

![Playlists Tab](https://github.com/werwolf2303/SpotifyXP/assets/133925958/561c0d79-0f81-4f37-bd6d-8c0c658464e6)

**Comment by werwolf2303** [comment]
I see the library I am using doesnt automatically fetch all songs

**Comment by werwolf2303** [comment]
I commited some code to hopefully fix that

**Comment by lesar8** [comment]
> I made a commit that changed some code to hopefully fix that

Something probably went wrong, SpotifyXP hanging when fetching playlist songs. None of the tracks appears, only blank page.

![Hanging](https://github.com/werwolf2303/SpotifyXP/assets/133925958/c71dbd4d-f740-499e-89f5-a4980300d1e8)

**Comment by werwolf2303** [comment]
I can make it multi threaded that will solve it I guess

**Comment by werwolf2303** [comment]
Changed some code to make it multi threaded

**Comment by lesar8** [comment]
> Changed some code to make it multi threaded

It loads fine now, big thanks! 
I noticed there are some oddities with the "Legacy" skin since couple of previous builds. Honestly would be nice if the SpotifyXP window could be freely resized. But otherwise this is a dream, thanks again.

**Comment by werwolf2303** [comment]
The freely resizing is very difficult because every component is placed with x, y, width and height. There is already some code in the nightly builds that make resizing "work" but it has issues

**Comment by werwolf2303** [comment]
Can you list me the oddities

**Comment by lesar8** [comment]
> Can you list me the oddities

Hi, it's quite hard to describe but i will try (apologize for my terrible English..).

Firstly, the WINDOW width and height was not fully stretched to show the last song of playlist. In my image example, "Girl In Mine" is not the last song but "Rubycon" is, but you could not see and select it.
![Problem1](https://github.com/werwolf2303/SpotifyXP/assets/133925958/27ebd607-1049-4e41-934e-3bd3d6e09e21)

If you press Ctrl+A and Ctrl+C to copy all of the songs name and paste to Notepad, you will see "Rubycon" is actually the last song.
![Notepad](https://github.com/werwolf2303/SpotifyXP/assets/133925958/99ea84a3-1e37-4e0b-a0b0-cf14f11ed913)

Secondly, the tabs position was disorganized and not nice to look at. 
![Problem2](https://github.com/werwolf2303/SpotifyXP/assets/133925958/1aeee3e7-48cf-4766-b86e-6b64b6103b63)

The "DarkGreen" theme and an official build did not have this problem.
![Normal](https://github.com/werwolf2303/SpotifyXP/assets/133925958/7dcfc81b-03e9-4f07-88ad-9ae6450de86b)

**Comment by werwolf2303** [comment]
Ok I will look into that

**Comment by werwolf2303** [comment]
Whats your language?

**Comment by lesar8** [comment]
> Whats your language?

My language is Thai.

**Comment by werwolf2303** [comment]
Would you like to translate SpotifyXP?

**Comment by lesar8** [comment]
> Would you like to translate SpotifyXP?

I don't think my English is good enough but my friends are, maybe I can ask them for help..

**Comment by werwolf2303** [comment]
Ok if you need any help just ask
