### ISSUE TITLE
Java Application for Windows Xp

### ISSUE THREAD

**Issue by Timi1543** [werwolf2303/SpotifyXP#34]
Hello
I tested the Application on Windows 11 running the latest Java and it works perfect. You said you tested the Application on Windows Xp Home 32 Bit can i ask you what version of java do you used. Can you add the exe for Java 32bit XP to the download list this woud be verry nice.

**Comment by Timi1543** [comment]
Und ich habe gerade in deinem Profil gesehen das du aus deutschland kommst. Ich finde das projekt wirklich sher cool und würde es sehr gern benutzen. Ich habe momentan noch für 70 Tage Spotify Premium. Vielleicht verstehe ich ja einfach nicht was ich tun soll denn ich habe eine Java version für windows xp gefunden doch diese sagt coulnt find mainderectory oder so was und auf meinem windows 11 laptop machte ich dasselbe und es funktionierte direkt. Kannst du mir helfen? Liebe Grüsse 
PS: Bist du schon drann oder willst du das Programm nicht auf Deutsch übersetzten?

**Comment by werwolf2303** [comment]
Are you using a translator or are you speaking german natively?

**Comment by Timi1543** [comment]
Im speaking german natively but im sorry my grammer isn't that good

**Comment by werwolf2303** [comment]
Ok achso. Die Möglichkeit zu übersetzen ist schon implementiert das kannst du sogar selbst machen. Ich arbeite heute daran den support für das wiederherzustellen. Ich biete dir an das du die übersetzung übernimmst. Dazu erstellst du einfach eine de.json in src/main/resources/lang schaue einfach in die en.json für hilfe

**Comment by Timi1543** [comment]
sorry aber ich versehe nichts 
ich bin über einen youtuber auf das projekt aufmerksam geworden aber versehe 0 von programmieren ich möchte einfach musik auf windows xp hören

**Comment by Timi1543** [comment]
Die Sprache ist mir im moment auch egal aber ich kreige das programm nicht zum laufen es kommt immer Could not find the main class. Der Zip ordner ist auf meinem desktop und die .jar datei auch.
Auf meinem Windows 11 Laptop funktionierte es auf anhieb beim ausführen der .jar datei
Sorry und Liebe Grüsse

**Comment by werwolf2303** [comment]
ok dann mach ich auch das übersetzen. Der letzte feature release für die nächste Zeit steht an 2.0. Suche im internet nach "last java version for Windows XP" da müsstest du eine kompatible java version finden

**Comment by Timi1543** [comment]
für 32 bit?

**Comment by werwolf2303** [comment]
Java 1.8.0 152 ist die letzte version wo noch der installer funktioniert

**Comment by werwolf2303** [comment]
java 8 gibts für 32,64,arm64 und noch andere

**Comment by Timi1543** [comment]
Funktioniert das auch auf service pack 2?

**Comment by werwolf2303** [comment]
service pack 3 wurde nur getestet. SP3 gibts als iso soweit ich noch weiß

**Comment by Timi1543** [comment]
ich versuchs mal

**Comment by Timi1543** [comment]
Hey danke vielmal.
Ich war einfach dumm.
Das Projekt ist so eine gute idee also mach weiter so.
Wenn du noch zeit hättest könntest du mir ja noch erklären wie ich die sprache ändere

**Comment by werwolf2303** [comment]
Der support für die änderung der sprache ist erst ab 2.0

**Comment by Timi1543** [comment]
ok danke vielmal
