### ISSUE TITLE
Errors out on "Creating dot menus..." w/ Windows XP pro 32-bit.

### ISSUE THREAD

**Issue by vacuoomm** [werwolf2303/SpotifyXP#35]
I have tried everything to get this to work. At a loss at what to do. Please help, as I would love to get this working!!!

![image](https://github.com/werwolf2303/SpotifyXP/assets/141374431/2b5dac4c-ac6d-45e9-9fe4-a82cf05d37ce)

![image](https://github.com/werwolf2303/SpotifyXP/assets/141374431/69433732-3e5a-4fa6-b3a7-07ea3d09a39c)

**Comment by werwolf2303** [comment]
I reverse engineered this part. The nightly versions are very unstable. When 2.0 is out this will be fixed

**Comment by vacuoomm** [comment]
Okay sounds good. I'm excited for working Spotify on XP! Your work is underappreciated.
