### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Yosemite73** [werwolf2303/SpotifyXP#36]
Hi,
I'm currently running version 1.9 but when I update to version 2.0.0 I get an error (see picture). I've tried to update it using the new SpotifyXP.jar file, but that also doesn't work, same error.  My Java version is build 1.8.0_381-b09 under Windows7.
Thanks. 

![error](https://github.com/werwolf2303/SpotifyXP/assets/45720046/fb10a078-c53d-4cf2-8af6-8e097f8eeb19)

**Comment by werwolf2303** [comment]
Install vlc

**Comment by Yosemite73** [comment]
Yup, that did the trick! Thanks!!
