### ISSUE TITLE
Unable to load library libvlc

### ISSUE THREAD

**Issue by HEB2021** [werwolf2303/SpotifyXP#37]
Running the latest version of spotifyXP I get an unable to load library libvlc this is the same on windows 10 with latest java, windows vista with java 202 not entirely sure what to do it happens when spotify xp says creating canvas player

**Comment by maclefou** [comment]
I have it too with windows 11, thats weird

**Comment by werwolf2303** [comment]
I am using libvlc to display a video. If this problem persists even when vlc is installed please open an issue on libvlc I am using an older version compatible with java 8

**Comment by werwolf2303** [comment]
I am using libvlc version 4.4.0
