### ISSUE TITLE
Stuck on creating api...

### ISSUE THREAD

**Issue by rotaz4** [werwolf2303/SpotifyXP#38]
after installation si spotifyxp remains stuck in the startup screen creating api... and does not start.

Does anyone know how to solve? and what is the problem?

**Comment by werwolf2303** [comment]
Can you send me the output of java -jar SpotifyXP.jar --setup-complete --debug

**Comment by werwolf2303** [comment]
Can you send me the contents of AppData/SpotifyXP/config.properties of course without your username and password

**Comment by werwolf2303** [comment]
Change HIGHT to HIGH

**Comment by werwolf2303** [comment]
Then it should work

**Comment by werwolf2303** [comment]
This will be fixed in the next update

**Comment by werwolf2303** [comment]
Issue is fixed locally. There was a typo in the code
