### ISSUE TITLE
Error when activating random reproduction in playlist

### ISSUE THREAD

**Issue by ciberfan** [werwolf2303/SpotifyXP#39]
[org.json.JSONException: JSONObject["items"] not found.] org.json.JSONObject.get(JSONObject.java:570)
org.json.JSONObject.getJSONArray(JSONObject.java:763)
com.spotifyxp.api.SpotifyAPI$1.run(SpotifyAPI.java:246)
java.lang.Thread.run(Thread.java:745)

Thanks for this wonderful program, I am a new follower. As the title says, by activating random reproduction, this error occurs immediately in the next reproduction of the song.

**Comment by werwolf2303** [comment]
Are you using a nightly build?

**Comment by werwolf2303** [comment]
What do you mean by "Random Reproduction"

**Comment by ciberfan** [comment]
I use the version available for download. I don't know how to download the latest version with fixes. I want to say that the error occurs when the shuffle option is enabled in the player.

**Comment by ciberfan** [comment]
hi again, not fixed, using last nightly build.


![Dibujo](https://github.com/werwolf2303/SpotifyXP/assets/143445988/5118f656-8042-4c0d-b61f-370ef2bd73ba)

**Comment by werwolf2303** [comment]
I am fixing it when I am not sick anymore

**Comment by ciberfan** [comment]
Thanks, i really apreciated your work, hope you'll be ok. God bless you.

**Comment by werwolf2303** [comment]
Shuffle didnt work since the day I added it into the UI. For some reason librespot-java doesnt handle shuffle correctly. I am going to disable this feature
