### ISSUE TITLE
Why is it that every time it loads a song, it shows that an exception occured?

### ISSUE THREAD

**Issue by Jri-creator** [werwolf2303/SpotifyXP#40]
When I use SpotifyXP, playing a song generates an exception on my end. This exception states:
[javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorExcepion: PKIK path building failed:]
so on, so on.
Why does it do this, and can it be fixed? Is it an issue on my end?

**Comment by ciberfan** [comment]
> When I use SpotifyXP, playing a song generates an exception on my end. This exception states: [javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorExcepion: PKIK path building failed:] so on, so on. Why does it do this, and can it be fixed? Is it an issue on my end?

same here *-*

[javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
sun.security.ssl.Handshaker.processLoop(Handshaker.java:969)
sun.security.ssl.Handshaker.process_record(Handshaker.java:904)
sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
java.net.URL.openStream(URL.java:1038)
com.spotifyxp.listeners.PlayerListener.onTrackChanged(PlayerListener.java:119)
com.spotifyxp.deps.xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$trackChanged$8(Player.java:1129)
com.spotifyxp.deps.xyz.gianlu.librespot.player.Player$EventsDispatcher$$Lambda$158/22771602.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by werwolf2303** [comment]
Its a certificate error: https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ
