### ISSUE TITLE
A couple of exceptions here and there...

### ISSUE THREAD

**Issue by Ethaniel-404** [werwolf2303/SpotifyXP#42]
... I mean, technically the program keeps working, they are more like popups. Maybe you'll recognize something...?

WIndows XP SP3, Java 8 152, VLC 3.0.18. This was inside VMWare.

![error1](https://github.com/werwolf2303/SpotifyXP/assets/52855817/3cc3c438-e6f2-4d1e-9b5f-f89546faeb42)
![error2](https://github.com/werwolf2303/SpotifyXP/assets/52855817/562daefc-e6b5-4322-ad96-63a025864d18)

**Comment by werwolf2303** [comment]
Download the newest inside the Actions tab and let me know if it still happens

**Comment by Ethaniel-404** [comment]
Downloaded, compiled, and ran the new build. The previous errors are gone, now I'm just getting this one. It repeats every time you try to enter to the Hot List section.

![error3](https://github.com/werwolf2303/SpotifyXP/assets/52855817/7dd73968-3c40-49cb-bb8a-b6bd648b463f)

**Comment by werwolf2303** [comment]
Does the hot list tab load with the error?

**Comment by Ethaniel-404** [comment]
I can get inside, but no content. It remains empty.

![error4](https://github.com/werwolf2303/SpotifyXP/assets/52855817/361a8b55-2c94-458f-b068-97d93d18fb67)

**Comment by Ethaniel-404** [comment]
Update: If I use the Refresh command trying to update the Hot List, the error count goes up by 1, same as before. But if I click on one of the items in the Error queue, it triggers another exception. No hard crash, music keeps playing.

![error5](https://github.com/werwolf2303/SpotifyXP/assets/52855817/7fbc55c9-0015-4a3d-9703-71bf1840afb2)
![error6](https://github.com/werwolf2303/SpotifyXP/assets/52855817/504112b5-a57e-4f48-8c61-ad98a8e71c0e)

**Comment by werwolf2303** [comment]
So this json exception complains about that the object "tracks" was not found that means the Spotify API returned something that my code didnt expect. I am very happy that this doesnt make the client unstable. When I am back from school I will make a debug build for you that ouputs the JSON so that you can send me that

**Comment by werwolf2303** [comment]
Grab the SpotifyXP.jar: https://github.com/werwolf2303/SomeStuff/releases/tag/v1.5

**Comment by Ethaniel-404** [comment]
No particular changes, Hot List still presents the same error, but if I click on one of them, the message is... shorter?

![error7](https://github.com/werwolf2303/SpotifyXP/assets/52855817/aa802cfe-ec7d-48c1-8c6f-2bb6418e1632)

The UI still reports v2.0.0 public beta, even when your debug version says 1.5. Is this by design, or do I need to do some sort of deeper uninstall? So far, I've been deleting the SpotifyXP folder on the user profile.

**Comment by werwolf2303** [comment]
Dont install it just run "java -jar SpotifyXP.jar --setup-complete" and send me the output. It should dump the JSON in the Hot List

**Comment by Ethaniel-404** [comment]
If you're expecting a .json file, I'm not getting one with that command. But when I enter the Hot List, the «tracks not found» error triggers twice, and the content is the same I showed you in the previous image:

[org.json.JSONException: JSONObject["tracks"] not found.] org.json.JSONObject.get(JSONObject.java:570)
org.json.JSONObject.getJSONArray(JSONObject.java:763)
com.spotifyxp.panels.ContentPanel.fetchHotlist(ContentPanel.java:3215)
com.spotifyxp.panels.ContentPanel$102.run(ContentPanel.java:3026)
java.lang.Thread.run(Unknown Source)

Hope that helps.

**Comment by werwolf2303** [comment]
It dumps that into the cmd console

**Comment by Ethaniel-404** [comment]
I'm really sorry about the delay, weekend has been a whirlwind. I see no JSON output on the console when I trigger the error. Am I missing something...?

![error10](https://github.com/werwolf2303/SpotifyXP/assets/52855817/56bd41ae-b675-4769-b1c4-02d3a20ebf1b)

**Comment by werwolf2303** [comment]
Do you have Spotify Premium?

**Comment by Ethaniel-404** [comment]
No, I use the free version.

**Comment by werwolf2303** [comment]
Thats normal the Spotify API requires Spotify Premium
