### ISSUE TITLE
Startup message

### ISSUE THREAD

**Issue by Gonimbrasia** [werwolf2303/SpotifyXP#43]
Is it possible to change the amount of time it takes for SpotifyXP to think it's stuck while starting up?
I get this message every time using the official build, even if it then starts normally.
![Clipboard01](https://github.com/werwolf2303/SpotifyXP/assets/110612260/8ff0ee52-d1c8-4c45-9d0b-79657b0b9991)
I can get rid of it by building after changing `if (s > 10) {` to `if (s > 20) {` in Initiator.java.

**Comment by werwolf2303** [comment]
You can just press "No" and ignore it

**Comment by werwolf2303** [comment]
I would wait a little bit SpotifyXP is getting Last.fm integration
