### ISSUE TITLE
Sound stutter since commit "9a1df53"

### ISSUE THREAD

**Issue by lesar8** [werwolf2303/SpotifyXP#44]
Hi, i'm back again. Currently i'm stuck with build eb4d7f3, because the commit 9a1df53 introduced the sound stutter problem any time I manually change tracks on my Playlist. Sound seems to stutter every few second and the CPU load goes up to 100%, to the point where i need to kill the Process. 

The commit 9a1df53 seems to fix something related to Spotify device control, not sure why it made the sound stutter.

**Comment by werwolf2303** [comment]
Thats normal because librespot must tell Spotify that the track changed and sends some traffic for that reason. It should normalize itself after a few seconds.

**Comment by lesar8** [comment]
The problem is, it didn't normalize as it should be and SpotifyXP keep hanging. I'm then forced to kill the process ..

**Comment by werwolf2303** [comment]
I added a queue to hopefully slow these down a little bit

**Comment by werwolf2303** [comment]
When this issue persists please open a new issue at https://github.com/SpotifyXP/SpotifyXP
