### ISSUE TITLE
[bug] SpotifyXP is already running!

### ISSUE THREAD

**Issue by lovebug0706** [werwolf2303/SpotifyXP#5]
I have no other processes of Java open. When i click OK, it closes out. when i click Cancel, it closes out. SpotifyXP is not open at all. I have tried restarting my computer, and nothing comes up on the command prompt. No code. I would love to use this again, but i cant at the moment. Hopefully you can fix it!
- MacBack

**Comment by werwolf2303** [comment]
This happens when you force SpotifyXP to close just delete the LOCK file in appdata/SpotifyXP

**Comment by lovebug0706** [comment]
Thanks!
