### ISSUE TITLE
TrackUtils line 94

### ISSUE THREAD

**Issue by HEB2021** [werwolf2303/SpotifyXP#8]
Error opening playlists tab on windows xp sp3 with java 8u152 error reads TrackUtils line 94 NullPointerException. CMD log says

C:\Documents and Settings\Hamish\Desktop>java -jar SpotifyXP.jar --setup-complet
e
SpotifyXP [INFO ] Player ready
SpotifyXP [INFO ] Building ContentPanel
SpotifyXP [INFO ] Done building ContentPanel
Apr 08, 2023 9:11:04 PM org.apache.commons.httpclient.HttpMethodDirector execute
WithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request:
Connection timed out: connect
Apr 08, 2023 9:11:04 PM org.apache.commons.httpclient.HttpMethodDirector execute
WithRetry
INFO: Retrying request
Apr 08, 2023 9:11:25 PM org.apache.commons.httpclient.HttpMethodDirector execute
WithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request:
Connection timed out: connect
Apr 08, 2023 9:11:25 PM org.apache.commons.httpclient.HttpMethodDirector execute
WithRetry
INFO: Retrying request
Apr 08, 2023 9:11:46 PM org.apache.commons.httpclient.HttpMethodDirector execute
WithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request:
Connection timed out: connect
Apr 08, 2023 9:11:46 PM org.apache.commons.httpclient.HttpMethodDirector execute
WithRetry
INFO: Retrying request
SpotifyXP [THROWABLE ] java.net.TwoStacksPlainSocketImpl.socketConnect(Native Me
thod)
SpotifyXP [THROWABLE ] java.net.AbstractPlainSocketImpl.doConnect(Unknown Source
)
SpotifyXP [THROWABLE ] java.net.AbstractPlainSocketImpl.connectToAddress(Unknown
 Source)
SpotifyXP [THROWABLE ] java.net.AbstractPlainSocketImpl.connect(Unknown Source)
SpotifyXP [THROWABLE ] java.net.PlainSocketImpl.connect(Unknown Source)
SpotifyXP [THROWABLE ] java.net.SocksSocketImpl.connect(Unknown Source)
SpotifyXP [THROWABLE ] java.net.Socket.connect(Unknown Source)
SpotifyXP [THROWABLE ] java.net.Socket.connect(Unknown Source)
SpotifyXP [THROWABLE ] java.net.Socket.<init>(Unknown Source)
SpotifyXP [THROWABLE ] java.net.Socket.<init>(Unknown Source)
SpotifyXP [THROWABLE ] org.apache.commons.httpclient.protocol.DefaultProtocolSoc
ketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
SpotifyXP [THROWABLE ] org.apache.commons.httpclient.protocol.DefaultProtocolSoc
ketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
SpotifyXP [THROWABLE ] org.apache.commons.httpclient.HttpConnection.open(HttpCon
nection.java:707)
SpotifyXP [THROWABLE ] org.apache.commons.httpclient.HttpMethodDirector.executeW
ithRetry(HttpMethodDirector.java:387)
SpotifyXP [THROWABLE ] org.apache.commons.httpclient.HttpMethodDirector.executeM
ethod(HttpMethodDirector.java:171)
SpotifyXP [THROWABLE ] org.apache.commons.httpclient.HttpClient.executeMethod(Ht
tpClient.java:397)
SpotifyXP [THROWABLE ] org.apache.commons.httpclient.HttpClient.executeMethod(Ht
tpClient.java:323)
SpotifyXP [THROWABLE ] com.spotifyxp.utils.ConnectionUtils.makePingToServer(Conn
ectionUtils.java:100)
SpotifyXP [THROWABLE ] com.spotifyxp.analytics.Analytics.<init>(Analytics.java:2
1)
SpotifyXP [THROWABLE ] com.spotifyxp.Initiator.main(Initiator.java:189)
SpotifyXP [INFO ] SpotifyXP needed 2 Minutes 14 Seconds to start
Exception in thread "Thread-8" org.json.JSONException: JSONObject["next"] is not
 a string (class org.json.JSONObject$Null : null).
        at org.json.JSONObject.wrongValueFormatException(JSONObject.java:2702)
        at org.json.JSONObject.getString(JSONObject.java:861)
        at com.spotifyxp.panels.ContentPanel$1.run(ContentPanel.java:185)
        at com.spotifyxp.threading.StoppableThread.run(StoppableThread.java:37)
        at java.lang.Thread.run(Unknown Source)

**Comment by werwolf2303** [comment]
I will look into that today when I am home

**Comment by werwolf2303** [comment]
This is a bug from librespot. SpotifyXP tries to queue songs but librespot fails to do that

**Comment by werwolf2303** [comment]
You can ignore that in the next release this message gets changed to something like this : "SpotifyXP failed to queue the tracks"
